name: Installer Function Tests (Mock Image)

on: 
  # Trigger when PR is submitted to main
  pull_request:
    branches:
      - main
      - add-pull-request-function-tests #Testing only

  # manual trigger
  workflow_dispatch:

jobs:
  function-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6
      - uses: actions/checkout@v2

      - name: Run Function Tests
        run: |
          if: contains(steps.pr-labels.outputs.labels, '  ok-to-test  ')
          echo "Running Pull Request Function Tests ..."
          ./common/scripts/pull-request-function-test.sh
        env:
          COLLECTIVE_TOKEN: ${secrets.COLLECTIVE_TOKEN}
