name: Installer Function Tests (Mock Image)

on: 
  # Trigger when PR is submitted to main
  pull_request:
    types: [ labeled ]
    branches:
      - main
      - add-pull-request-function-tests #Testing only

  # manual trigger
  workflow_dispatch:

jobs:
  function-test:
    if: ${{ github.event.label.name == 'ok-to-test' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Apply YQ
        uses: mikefarah/yq@3.4.0
      - name: Run Function Tests (Requires 'ok-to-test' label)
        run: |
          echo "Running Pull Request Function Tests ..."
          bash ./common/scripts/pull-request-function-test.sh
        env:
          COLLECTIVE_TOKEN: ${secrets.COLLECTIVE_TOKEN}
      - name: removelabel
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.FF_TOKEN}}
          label: ok-to-test
          type: remove
